version: '3.8'

services:
  servico_a:
    build:
      context: ./servico_a
      dockerfile: Dockerfile
    container_name: servico_a
    ports:
      - "8080:8080"

  servico_b:
    build:
      context: ./servico_b
      dockerfile: Dockerfile
    container_name: servico_b
    ports:
      - "8081:8080"