services:
  servico_b:
    build:
      context: ./servico_b
      dockerfile: Dockerfile
    container_name: servico_b
    ports:
      - "8081:8080"  # Porta externa 8081 → interna 8080
    networks:
      - rede_interna

  servico_a:
    build:
      context: ./servico_a
      dockerfile: Dockerfile
    container_name: servico_a
    ports:
      - "8080:8081"  # Porta externa 8080 → interna 8080
    depends_on:
      - servico_b
    networks:
      - rede_interna

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - rede_interna

  otel-collector:
    image: otel/opentelemetry-collector:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - zipkin
    networks:
      - rede_interna


networks:
  rede_interna:
